### ISSUE TITLE
You are requring 1.9.0+ of PythonCollector which hasn't been released yet. Typo?

### ISSUE THREAD

**Issue by pjohnston** [linkslice/ZenPacks.community.HAProxy#2]

**Comment by linkslice** [comment]
In my dev VM PythonCollector says it's 1.9, but it appears I grabbed the 'develop' branch from github. I do not think 1.9 nor any specific version is necessary. Can you try again?

**Comment by pjohnston** [comment]
Hi Bryan,
I see you removed the version dependency from setup.py, that did the trick. Thanks!
Best regards,
Paul.

**Comment by linkslice** [comment]
Let me know how it works. I've been a little nervous about this one because I wasn't able to test.
