### ISSUE TITLE
install steps / not working

### ISSUE THREAD

**Issue by celesteking** [linkslice/ZenPacks.community.HAProxy#4]
This has worst possible documentation.

What are steps on installing the snmp agent? It doesn't work over here.
```
# perl haproxy.pl 
Warning: no access control information configured.
  (Config search path: /etc/snmp:/usr/share/snmp:/usr/lib64/snmp:/root/.snmp)
  It's unlikely this agent can serve any useful purpose in this state.
  Run "snmpconf -g basic_setup" to help you configure the Haproxy.conf file for this agent.

# snmpwalk  -v3 -a SHA -l authNoPriv -u reader -A xx 127.0.0.1 1.3.6.1.4.1.29385.106
SNMPv2-SMI::enterprises.29385.106 = No Such Object available on this agent at this OID
```

**Comment by celesteking** [comment]
Well, you had to **restart** the snmpd daemon, not just reload it with SIGHUP.

**Comment by celesteking** [comment]
I'm getting a lot of errors in zenperfsnmp.log:

## 1
2020-05-01 11:22:22,261 WARNING zen.zenperfsnmp: Error reading value for ['b:pop3'] (1.3.6.1.4.1.29385.106.1.1.44.13.0) on xx
2020-05-01 11:22:22,261 ERROR zen.zenperfsnmp: SNMP get returned empty value: xx 1.3.6.1.4.1.29385.106.1.2.40.13.2
2020-05-01 11:22:22,262 WARNING zen.zenperfsnmp: Error reading value for ['in2.mailproxy'] (1.3.6.1.4.1.29385.106.1.2.40.13.2) on xx
2020-05-01 11:22:22,262 ERROR zen.zenperfsnmp: SNMP get returned empty value: xx 1.3.6.1.4.1.29385.106.1.0.39.4.0

and so on, it seems like that's happening for every `show stat` line. 

`2020-05-01 11:22:22,291 INFO zen.zenperfsnmp: xx: Detected 216 bad oids this cycle`
Funny thing is that I've got only 40 `show stat` lines.

## 2
Getting following alerts in events after modelling:

device	zeneventd
message 
Internal exception processing event: AttributeError("'HAProxyDevice' object has no attribute 'getPhysicalRoot'",)/{'severity': 0, 'first_seen_time': 1588354109938L, 'monitor': u'localhost', 'actor': {'element_identifier': u'xx', 'element_sub_type_id': 2, 'element_uuid': u'7f8ca97f-e9b4-4748-8b9f-f24cd4a7bf91', 'element_type_id': 1, 'element_sub_identifier': u'smtp'}, 'summary': u'IP Service smtp back up', 'agent': u'zenstatus', 'created_time': 1588354109938L, 'details': [{'name': u'manager', 'value': [u'xx']}, {'name': u'zenoss.device.ip_address', 'value': [u'xx']}], 'event_group': u'TCPTest', 'event_key': u'', 'event_class': u'/Status/IpService', 'uuid': u'2e20fdce-8bd1-11ea-bc41-00163ecc2406'}

summary	Internal exception processing event: AttributeError("'HAProxyDevice' object has no attribute 'getPhysicalRoot'",)

**Comment by linkslice** [comment]
> This has worst possible documentation.

yeah, it's not great, I look forward to your diff against readme.md. To be fair, your bug report is pretty bad too! :-)

What Zenoss version? Did you restart Zenoss after pack install? Any errors during pack install? How was the device added? Have you checked the zPythonClass?

**Comment by celesteking** [comment]
zenoss 4.2.x. Have restarted it. Pack installed via UI, no errors. 
Device wasn't added, it was already present. I've changed the class to `/Server/Linux/HAProxy`, which wasn't documented either. 
Errors outlined in **1** are still there. Is that because some frontends/backends don't receive traffic? How do I make them go away?

Update: Errors in **2** are gone after zenoss restart and have no longer appeared

**Comment by linkslice** [comment]
Can you post an snmpwalk against 1.3.6.1.4.1.29385.106?

**Comment by celesteking** [comment]
here you go: [walk.txt](https://github.com/linkslice/ZenPacks.community.HAProxy/files/4630852/walk.txt)

**Comment by linkslice** [comment]
hmm, if you push traffic to the frontends/backends do values start reporting correctly after that? If so, the script could maybe be modified to return zeros. I don't have access to an haproxy system to test that.
